### ISSUE TITLE
update video title and description

### ISSUE THREAD

**Issue by stevemar** [IBM/Predictive-Market-Stress-Testing#11]
the video associated with this journey lacks a description and is entitled "zoom 0" -- whoever has access to the "IBM FinTech" account on Youtube should clean that up ASAP -- https://www.youtube.com/watch?v=6Ta6tve51w4

**Comment by ljbennett62** [comment]
@stevemart - i will work with Raheel who owns it to fix it.

**Comment by raheelzubairy** [comment]
@stevemart sorry, it took a while, but done now. Thanks
