### ISSUE TITLE
run.py returns server 500 error on /api/portfolionames

### ISSUE THREAD

**Issue by oocyte** [IBM/Predictive-Market-Stress-Testing#7]
I had to update the following code in order to get the deployment to work on bluemix. Is it my own environment setup?

portfolio_names = [portfolio['name'] for portfolio
		      in investmentportfolio.Get_Portfolios()['portfolios']]

If the change is not in place, Application Run logs report:
127.0.0.1 - - [17/Aug/2017 20:41:51] "GET /api/portfolionames HTTP/1.1" 500 -

**Comment by raheelzubairy** [comment]
@oocyte the code is performing the same action. 
I have not seen this issue with any deployment to Bluemix.
